### PR TITLE
Release 0.9.0

### PR DESCRIPTION
**Pull request by JirkaChadima**
- Merge this PR with a merge commit.
- If you want to release this, you'll need to merge to one of the release branches.
- Don't delete the develop branch!

### CODE REVIEW

**Comment by hynek-urban** [comment]
Just one note - a few months ago, we've moved the swarmProviderUrl parameter from per-user configuration to per-api-instance configuration. The reason for this was possible data consistency issues if different users used different swarm networks, all being simply denoted as "swarm://".

Therefore, I would suggest not exposing this setting to the user and maintain a single swarm gateway for the whole API instance instead. Alternatively, some extra measures to ensure data consistency would probably be needed.

**Comment by hynek-urban** [comment]
Considering this a little bit more, I'm starting to think that maybe it's ok as it is. There is supposed to be a single swarm network - _the_ swarm network - anyway. If you, as a user, put a gateway to another network, then the data of your hotel will be corrupt from the point of view of other users of the WT platform and it's your responsibility and your fault.

Thoughts?

**Comment by JirkaChadima** [comment]
> Thoughts?

It's, as usual, slightly more complicated :-) I know of three possible concepts of "network" in Swarm:

1. `bzznetworkid` - arbitrary integer, `0` is the default one
1. `bootnodes` - list of initial nodes your node connects to (necessary until autodiscovery is implemented)
1. `version` - swarm versions are usually not exactly compatible with each other (alpha software)

And I *think* you cannot access any of these information via the remotely accessible HTTP API. So we have no way of checking compatibility in-between nodes. I can imagine there will eventually be a swarm testnet and a mainnet (when the incentive layer is finished), but until then, I think it's safe to say there should be only one public network revolving around swarm-gateways.net. So I would keep the options available to the users (for now).

From the architectural point of view, I think the endgame for wt-write-api would actually be to bundle a local swarm node with it. It feels more "right" to me than using a potentially compromised gateway somewhere in the wild (incentivization, encryption and possibly other issues might arise in that model). If we also presume that this should run in a private network, it really does not make sense to use a Swarm gateway in a different location.

So I would keep the options exposed and move the responsibility to the users... For now. But I'm pretty sure that if wt-write-api takes off, we will have to think about this again.

**Comment by hynek-urban** [comment]
Understood. However, if the endgame is indeed bundling a swarm node together with wt-write-api then exposing the swarm provider url to the user sounds like a step backwards.

Anyway, feel free to merge this based on your consideration. I think it's a viable route either way.

**Comment by JirkaChadima** [comment]
The end game is probably very far away... And in the meantime I think it might be benefical for somebody. Or maybe it's useless and I'm wrong :)

**Pull request merged**
